name: 'Deta Release'

on:
  workflow_dispatch:
    inputs:
      notes:
        type: string
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node Env
        uses: actions/setup-node@v3

      - name: Export Version 
        run: |
          SPACE_VERSION=$(node -e "console.log(require('./package.json').version);")
          SPACE_NOTES=$([ -n "${{ inputs.notes }}" ] && echo ${{ inputs.notes }} || echo "")
          echo "Which version will be released？=> $SPACE_VERSION ;"
          echo "SAPCE_NOTES: $SPACE_NOTES"
          echo "SPACE_VERSION=$SPACE_VERSION" >> $GITHUB_ENV
          echo "SPACE_NOTES=$SPACE_NOTES" >> $GITHUB_ENV

      - name: Release
        uses: lizheming/deta-action@1.0.1
        with:
          access_token: ${{ secrets.space_access_token }}
          id: ${{ secrets.space_id }}
          version: ${{ env.SPACE_VERSION }}
          notes: ${{ env.SPACE_NOTES }}
          listed: true